PORT=3001
NODE_ENV=production
FRONTEND_URL=https://quotly-frontend.vercel.app

JWT_SECRET=aZ9kP2mXqL8nR4vT6wY1uI3oE5qA7sD2fG
JWT_EXPIRES_IN=7d

# ⬇ REMPLACE PAR TON URL SUPABASE (Settings > Database > URI)
DATABASE_URL=postgresql://postgres:MOTDEPASSE@db.XXXX.supabase.co:5432/postgres

GMAIL_USER=quotly.devis@gmail.com
GMAIL_PASS=xxxx xxxx xxxx xxxx
EMAIL_FROM=Quotly <quotly.devis@gmail.com>

PAYPAL_WEBHOOK_ID=VOTRE_WEBHOOK_ID
PAYPAL_CLIENT_ID=VOTRE_CLIENT_ID
PAYPAL_CLIENT_SECRET=VOTRE_CLIENT_SECRET
PAYPAL_MODE=live
PAYPAL_PLAN_PRO=SLGH8N66YPCAQ
PAYPAL_PLAN_TEAM=BXFT9S9669PWY
